baseURL = "https://D4vid378.github.io/"
languageCode = 'it-it'
title = 'CtrlAltCancDav'
theme = 'PaperMod'

[params]
    env = "production"
    title = "CtrlAltCancDav"
    description = "Il mio blog tech"
    author = "Davide"

    # Questo attiva la modalità profilo (foto + bio)
    [params.profileMode]
        enabled = true
        title = "Davide"
        subtitle = "Benvenuti nel mio blog"
        imageUrl = "https://github.com/D4vid378.png"
        imageWidth = 120
        imageHeight = 120

    # Questo aggiunge le icone social
    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/D4vid378"

        [[menu.main]]
    identifier = "posts"
    name = "Articoli"
    url = "/posts/"
    weight = 10

[[menu.main]]
    identifier = "tags"
    name = "Argomenti"
    url = "/tags/"
    weight = 20