baseURL = "https://D4vid378.github.io/"
languageCode = 'it-it'
title = 'CtrlAltCancDav'
theme = 'PaperMod'

[params]
    # Qui iniziano i parametri personalizzati
    env = "production"
    description = "Il mio blog tech"
    author = "Davide"

    [params.homeInfoParams]
        Title = "Ciao, sono Davide 👋"
        Content = "Benvenuti nel mio spazio digitale"

    [params.profileMode]
        enabled = true
        title = "CtrlAltCancDav"
        subtitle = "Tech Blogger"
        imageUrl = "https://github.com/D4vid378.png"
        imageWidth = 150
        imageHeight = 150

        [[params.socialIcons]]
            name = "github"
            url = "https://github.com/D4vid378"

            [[menu.main]]
    identifier = "posts"
    name = "Articoli"
    url = "/posts/"
    weight = 10

[[menu.main]]
    identifier = "tags"
    name = "Argomenti"
    url = "/tags/"
    weight = 20